# Generated by Django 5.0.4 on 2024-04-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0003_homework_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
