# Generated by Django 5.0.4 on 2024-04-17 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0012_alter_homework_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksolution',
            name='grade',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='homeworksolution',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
