# Generated by Django 5.0.4 on 2024-04-17 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0013_homeworksolution_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksolution',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='homeworksolution',
            name='teacher_comment',
        ),
    ]
